In [1]:
import numpy as np

In [2]:
import pandas as pd

#Numpy Array Operations:

1. Create a 1D NumPy Array:

In [3]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] )
print('Temperature for week1 is \n',temperatures_w1)

Temperature for week1 is
 [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

2. Inspection and Properties:

In [4]:
print('Shape os the array \n',temperatures_w1.shape)
print('Data type of array \n',temperatures_w1.dtype)
print('number of elements in the array \n',temperatures_w1.size)

Shape os the array
 (7,)
Data type of array
 float64
number of elements in the array
 7

3. Array Operations:

In [5]:
Fahrenheit=(temperatures_w1*9/5)+32
print('Temperature in Fahrenheit\n',Fahrenheit)

print(f'Maximum temperature for the week is {np.max(Fahrenheit)}F')
print(f'Minimum temperature for the week is {np.min(Fahrenheit)}F')
print(f'Mean temperature for this week is{np.mean(Fahrenheit):.2f}F')

Temperature in Fahrenheit
 [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum temperature for the week is 78.98F
Minimum temperature for the week is 69.44F
Mean temperature for this week is74.38F

4. Array Slicing and Indexing:

In [6]:
print('Temperature for the week is\n',temperatures_w1)

first_three=temperatures_w1[:3]
last_two=temperatures_w1[-2:]
middle_three=temperatures_w1[2:5]

print('\n Temperature for first three days are\n',first_three)
print('\nTemperature for weekend is\n',last_two)
print('\nTemperature for mid of week\n',middle_three)

Temperature for the week is
 [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

 Temperature for first three days are
 [22.5 25.3 20.8]

Temperature for weekend is
 [24.8 21.9]

Temperature for mid of week
 [20.8 23.4 26.1]

5. Create a 2D Array:

In [7]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

print('temperatures of two weeks:\n',temperatures)

temperatures of two weeks:
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

6. Inspect and Slice the 2D Array:

In [8]:
print(f'Shape of the array temperatures is: {temperatures.shape}')
print(f'Data type of the array temperatures is :{temperatures.dtype}')
print(f'Total number of elements in the array : {np.size(temperatures)}')

week1=temperatures[0]
print(f'week1 temperature : {week1}')
week1_end=temperatures[0,-2:]
print(f'First week end temp is: {week1_end}')
week2=temperatures[1]
print(f'Week 2 temperature :  {week2}')
week2_end=temperatures[1,-2:]
print(f'second week end temp : {week2_end}')

Shape of the array temperatures is: (2, 7)
Data type of the array temperatures is :float64
Total number of elements in the array : 14
week1 temperature : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
First week end temp is: [24.8 21.9]
Week 2 temperature :  [19.2 22.5 21.3 24.  23.5 22.8 20.1]
second week end temp : [22.8 20.1]

Pandas Series:

1. Creating Pandas Series:

In [9]:
marks=pd.Series([95, 92, 89, 85, 80 ],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'  ],name='marks')
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
Name: marks, dtype: int64

2. Indexing and Slicing:

In [10]:
print('mark of first rank student:',marks.iloc[0])
print('\nTop 3 Ranks ')
print(marks.loc[['Rank1','Rank2','Rank3']])
print('\n3rd rank mark: ',marks.iloc[2])

print('\ngreater than 90\n')
print(marks[marks>90])

mark of first rank student: 95

Top 3 Ranks
Rank1    95
Rank2    92
Rank3    89
Name: marks, dtype: int64

3rd rank mark:  89

greater than 90

Rank1    95
Rank2    92
Name: marks, dtype: int64

3. Manipulating Series:

In [11]:
marks['Rank1']=100

In [12]:
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
Name: marks, dtype: int64

In [13]:
updated_marks=marks.drop('Rank5')
updated_marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Name: marks, dtype: int64

In [14]:
CGPA=marks/10
CGPA

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
Name: marks, dtype: float64

In [15]:
print('upadted series:\n',updated_marks)
print('\nCGPA series :\n',CGPA)

upadted series:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
Name: marks, dtype: int64

CGPA series :
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
Name: marks, dtype: float64

Pandas DataFrame:

1. Creating Pandas DataFrame:

In [16]:
transactions_data={
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110 ],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],  
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North' ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400  ]
}

transactions=pd.DataFrame(transactions_data)
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

2. Data Exploration:

In [17]:
print('Dataframe :\n',transactions)

head_of_tansactions=transactions.head()

print('\nHead_of_tansactions : \n',head_of_tansactions)

tail_of_transactions=transactions.tail()

print('\nTail_of_transactions : \n',tail_of_transactions)

#transactions.shape

print('\nshape of Dataframe-transaction is : ',transactions.shape)

#transactions.columns

print('\ncoloum names are :\n',transactions.columns)

#transactions.dtypes
print('\ndata types of Transactions :\n' , transactions.dtypes)

Dataframe :
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head_of_tansactions :
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail_of_transactions :
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

shape of Dataframe-transaction is :  (10, 4)

coloum names are :
 Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

data types of Transactions :
 TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

Display only the 'ProductCategory' and 'Amount' columns.

In [18]:
transactions[['ProductCategory','Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

 Retrieve the last 3 columns of the DataFrame using iloc or loc.

In [19]:
transactions.iloc[:,-3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

 Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

In [20]:
transactions[(transactions['Region']=='North')& (transactions['Amount']>200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

Find the value counts for the 'ProductCategory' column.

In [21]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

 Find the unique values in the 'Region' column.

In [22]:
transactions['Region'].unique()

<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

 Group by 'Region' and find the mean amount for each region.

In [23]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

3. Manipulating the DataFrame:

●  Modify the 'Amount' for the transaction with TransactionID 102 to 165.

In [25]:
transactions.loc[transactions['TransactionID']==102,'Amount']=165

In [26]:
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Add a new column 'Discount' by calculating 10% of the 'Amount'.

In [28]:
transactions['Discount']=transactions['Amount']*10/100
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

Remove the row with TransactionID 109.

In [50]:
#row=transactions[transactions['TransactionID']==109]
transactions.drop(transactions[transactions['TransactionID']==109].index)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

 Delete the 'Discount' column from the DataFrame.

In [53]:
transactions.drop('Discount',axis=1)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400